<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="POWriteService_Client"
     targetNamespace="http://oracle.com/sca/soapservice/SOABasicServices/FileAdapterExample/POWriteService_Client"
     xmlns:tns="http://oracle.com/sca/soapservice/SOABasicServices/FileAdapterExample/POWriteService_Client"
     xmlns:inp1="http://www.example.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <!--<xsd:import namespace="http://www.example.org" schemaLocation="oramds:/apps/POSchema.xsd"/>-->
            <import namespace="http://www.example.org" schemaLocation="../Schemas/POSchema.xsd" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:PORequest"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
