<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.example.org" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://oracle.com/sca/soapservice/SOABasicServices/FileAdapterExample/POWriteService_Client"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/SOABasicServices/FileAdapterExample/POFileAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/POWriteService_Client.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PORequest" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/POFileAdapter.wsdl"/>
            <oracle-xsl-mapper:rootElement name="FileFormatObject" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT FEB 04 19:04:57 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:FileFormatObject>
         <ns0:PONumber>
            <xsl:value-of select="/ns0:PORequest/ns0:PONumber"/>
         </ns0:PONumber>
         <ns0:ProductName>
            <xsl:value-of select="/ns0:PORequest/ns0:ProductName"/>
         </ns0:ProductName>
         <xsl:if test="/ns0:PORequest/ns0:ProductCost lt 1000">
            <ns0:FinalCost>
               <xsl:value-of select="/ns0:PORequest/ns0:ProductCost * 0.9"/>
            </ns0:FinalCost>
         </xsl:if>
         <xsl:if test="/ns0:PORequest/ns0:ProductCost gt 1000">
            <ns0:FinalCost>
               <xsl:value-of select="/ns0:PORequest/ns0:ProductCost * 0.75"/>
            </ns0:FinalCost>
         </xsl:if>
         <ns0:Notes>
            <xsl:value-of select="concat ('Notes: ', /ns0:PORequest/ns0:ProductDescription,' : ', /ns0:PORequest/ns0:ProductName )"/>
         </ns0:Notes>
      </ns0:FileFormatObject>
   </xsl:template>
</xsl:stylesheet>
