<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GreetingService"
     targetNamespace="http://oracle.com/sca/soapservice/ConversionServices/HelloWorldSoa/GreetingService"
     xmlns:tns="http://oracle.com/sca/soapservice/ConversionServices/HelloWorldSoa/GreetingService"
     xmlns:inp1="http://www.lancefallon.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.lancefallon.org" schemaLocation="../Schemas/HelloWorldSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Request" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Response" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
